### ISSUE TITLE
there is an error when yarn install 

### ISSUE THREAD

**Issue by xiaobaifighting** [lixiaochjajo/SmartCity-Three#1]
the log is 
* ./js/Wall in ./node_modules/cache-loader/dist/cjs.js??ref--13-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--1-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/scene.vue?vue&type=script&lang=js&
Error from chokidar (/home/user/threeJs/SmartCity-Three/node_modules/core-js/modules): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/user/threeJs/SmartCity-Three/node_modules/core-js/modules/es.object.to-string.js'
.......

**Comment by lixiaochjajo** [comment]
The file name is wrong（js/wall.js   should be js/Wall.js ）
 I re-uploaded
 Pull it again
